name = "GreenWriter"
uuid = "e298cd2a-bb8b-47e7-b9a6-e75b86eaa6ce"
authors = ["Th√©o Galy-Fajou <theo.galyfajou@gmail.com> and contributors"]
version = "1.0.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"

[compat]
AbstractTrees = "0.4"
JuliaSyntax = "1"
julia = "1.10"
